# Docker Compose file to launch a local Drupal develpment cluster with an
# existing project.

version: '3'

services: 

  drp-mysql:
    user: "${HOST_UID}:${HOST_GID}"
    image: "mysql:5.7"
    ports:
       - "3306:3306" 
    volumes:
       - ./data/mysql:/var/lib/mysql
    env_file: .env 

  drp-php:
    image: drp-php
    volumes:
        - ${DRP_SITE_PATH}:/var/www/drupal
    expose:
      - 9000
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
    env_file: .env 

  drp-nginx:
    image: drp-nginx 
    volumes:
      - ${DRP_SITE_PATH}:/var/www/drupal
    ports:
      - "8080:8080"
    env_file: .env 

  
